### PR TITLE
feat: remove long timelock

### PR DESCRIPTION
**Pull request by gbirckan**

### CODE REVIEW

**Review by 0xfornax — COMMENTED** [review]
How do you propose we enforce long/short wait times if we don't have the two timelocks?

**Comment by gbirckan** [comment]
I don't think there's a need for two different wait times. The only use for LongTimelock is addNewCollateral, which could be changed to a shorter time.

**Comment by 0xfornax** [comment]
We want to have the two time options.

**Comment by gbirckan** [comment]
I disagree that the second one is necessary at this point. If ever needed, can be deployed later.

**Review by 0xfornax — APPROVED** [review]

**Pull request merged**
